"""Turns this app's settings into the two things the managed service needs:
an env file and an argv.

The env file exists because ``ctx.services`` launches a service as a bare
command line and hands it *this* process's environment — there is no per-service
env hook (see the workspace's ``src/apps/services.py``: ``subprocess.Popen(
shlex.split(start), cwd=package_dir)``). Putting the client secret on that
command line would leak it into every process listing on the host, so instead
the settings are written to ``.data/server.env`` (0600) and
``scripts/run_server.sh`` sources it.

Env var names are the upstream server's own, ported from the monolith's
``src/config/mcp.json`` entry for ``aw-google-workspace``.
"""
from __future__ import annotations

import os
import shlex
from pathlib import Path

from . import paths

DEFAULT_PORT = 8010
DEFAULT_TOOLS = "gmail drive calendar contacts docs sheets tasks"
DEFAULT_EMAIL = "fredericowu@gmail.com"
DEFAULT_ALLOWED_FILE_DIRS = "/opt/aw-workspace/.tmp"

VALID_TOOL_GROUPS = {
    "appscript", "calendar", "chat", "contacts", "docs", "drive",
    "forms", "gmail", "search", "sheets", "slides", "tasks",
}


def port_of(config: dict) -> int:
    try:
        return int(config.get("port") or DEFAULT_PORT)
    except (TypeError, ValueError):
        return DEFAULT_PORT


def tool_groups(config: dict) -> list[str]:
    """Unknown group names are dropped rather than passed through: argparse
    rejects them with a usage error and the server never starts, which shows
    up as a dead service with no obvious cause."""
    raw = str(config.get("tools") or DEFAULT_TOOLS).replace(",", " ").split()
    return [t for t in raw if t in VALID_TOOL_GROUPS] or DEFAULT_TOOLS.split()


def user_email(config: dict) -> str:
    return str(config.get("user_google_email") or DEFAULT_EMAIL).strip()


def redirect_uri(config: dict) -> str:
    explicit = str(config.get("oauth_redirect_uri") or "").strip()
    return explicit or f"http://localhost:{port_of(config)}/oauth2callback"


def build_env(config: dict, client_secret: str | None) -> dict[str, str]:
    """The environment the workspace-mcp process runs with."""
    port = port_of(config)
    env = {
        "PYTHONUNBUFFERED": "1",
        # OAUTHLIB_INSECURE_TRANSPORT: the callback is plain http on a
        # container-internal port, never exposed. Ported from the monolith.
        "OAUTHLIB_INSECURE_TRANSPORT": "1",
        "USER_GOOGLE_EMAIL": user_email(config),
        "WORKSPACE_MCP_PORT": str(port),
        "PORT": str(port),
        "WORKSPACE_MCP_CREDENTIALS_DIR": str(paths.credentials_dir()),
        # Still set the legacy name: older workspace-mcp releases only read
        # this one, and pin_version is user-editable.
        "GOOGLE_MCP_CREDENTIALS_DIR": str(paths.credentials_dir()),
        "ALLOWED_FILE_DIRS": str(config.get("allowed_file_dirs") or DEFAULT_ALLOWED_FILE_DIRS),
        "GOOGLE_OAUTH_REDIRECT_URI": redirect_uri(config),
    }
    client_id = str(config.get("google_oauth_client_id") or "").strip()
    if client_id:
        env["GOOGLE_OAUTH_CLIENT_ID"] = client_id
    if client_secret:
        env["GOOGLE_OAUTH_CLIENT_SECRET"] = client_secret
    return env


def write_env_file(package_dir: str, config: dict, client_secret: str | None) -> Path:
    """Write ``.data/server.env`` as shell-sourceable ``export`` lines, 0600."""
    path = paths.env_file(package_dir)
    body = "".join(
        f"export {key}={shlex.quote(value)}\n"
        for key, value in sorted(build_env(config, client_secret).items())
    )
    path.write_text(
        "# Generated by aw-app-google-workspace-mcp. Do not edit — regenerated\n"
        "# on every activate and on every settings save.\n" + body,
        encoding="utf-8",
    )
    os.chmod(path, 0o600)
    return path


def service_command(package_dir: str, config: dict) -> str:
    """Command line handed to ``ctx.services.register``.

    Goes through ``scripts/run_server.sh`` rather than invoking the venv
    binary directly, because the wrapper is what scrubs ``PYTHONPATH`` and
    sources the env file — neither of which a bare command line can do.
    ``ctx.services`` runs it with cwd = package_dir, so the path is relative.
    """
    tools = " ".join(tool_groups(config))
    return (
        "bash scripts/run_server.sh --single-user "
        f"--transport streamable-http --tools {tools}"
    )


def is_configured(config: dict, client_secret: str | None) -> bool:
    """Both halves of the OAuth client are needed before the server can do
    anything useful. It will still *start* without them (and serve tool
    definitions), but every call fails at auth — so this drives the UI's
    "not configured yet" state rather than gating the service."""
    return bool(str(config.get("google_oauth_client_id") or "").strip()) and bool(client_secret)
